#! /usr/bin/env python3
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
#
# Copyright © 2020 Shlomi Fish <shlomif@cpan.org>
#
# Distributed under the MIT license.

from zipfile import ZIP_DEFLATED, ZIP_STORED

import click

from rebookmaker import EbookMaker


@click.command()
@click.option("--output", help='the output EPub path')
@click.option("--compression",
              help='the zip compression to use', default="ZIP_DEFLATED")
@click.argument("jsonfn")
def main(output, jsonfn, compression):
    if compression == "ZIP_DEFLATED":
        compress = ZIP_DEFLATED
    elif compression == "ZIP_STORED":
        compress = ZIP_STORED
    else:
        raise Exception("Unknown compression")
    EbookMaker(compression=compress).make_epub(jsonfn, output)


if __name__ == '__main__':
    main()
